// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
var SITE_URL = "https://imtiyaz.lovable.app";
var projects = [
  {
    id: "automotive-vehicle-design",
    title: "Automotive & Vehicle Design",
    category: "Hard Surface \u2022 Concepts",
    client: "Personal Project",
    year: "2023 - 2025",
    tools: ["Blender", "Autodesk Maya", "Substance Painter", "After Effects"],
    description: "A versatile collection of high-fidelity vehicle assets ranging from vintage classics to futuristic sci-fi concepts. Demonstrates expertise in complex hard-surface topology, PBR texturing, and vehicle rigging for game engines.",
    imageCount: 20,
    videoCaptions: [
      "AI Generated from 3D Model",
      "Blending 3D physics with 2D post-processing using After Effects film grain and lighting effects."
    ],
    url: `${SITE_URL}/portfolio/automotive-vehicle-design`
  },
  {
    id: "3d-props-environment",
    title: "3D Props & Environment",
    category: "Game Assets \u2022 Architecture",
    client: "Asset Library",
    year: "2024",
    tools: ["Blender", "Maya", "Substance Painter"],
    description: "A diverse collection of game-ready 3D assets ranging from historical architecture to stylized props. Includes modular environment pieces, interactive objects, and hand-painted weapons\u2014demonstrating expertise in both modeling and texturing for game engines.",
    imageCount: 10,
    videoCaptions: [],
    url: `${SITE_URL}/portfolio/3d-props-environment`
  },
  {
    id: "ar-architecture",
    title: "AR Architecture Visualization",
    category: "Game Assets \u2022 Architecture",
    client: "University FYP",
    year: "2023",
    tools: ["Maya", "Unity", "AR Foundation"],
    description: "Final Year Project developing augmented reality visualizations of university buildings. Created detailed 3D models of campus architecture that can be viewed through AR, helping prospective students and visitors explore the campus virtually.",
    imageCount: 6,
    videoCaptions: [],
    url: `${SITE_URL}/portfolio/ar-architecture`
  },
  {
    id: "interior-visualization",
    title: "Interior & Exterior Design",
    category: "Game Assets \u2022 Architecture",
    client: "Various Clients",
    year: "2024",
    tools: ["Maya", "V-Ray", "Photoshop"],
    description: "Professional interior and exterior architectural visualizations for residential and commercial clients. These renders help clients visualize their spaces before construction, with attention to lighting, materials, and spatial design.",
    imageCount: 3,
    videoCaptions: [],
    url: `${SITE_URL}/portfolio/interior-visualization`
  },
  {
    id: "ai-enhanced-digital-media",
    title: "AI-Enhanced Digital Media",
    category: "AI-Enhanced Digital Media",
    client: "Various Clients",
    year: "2025",
    tools: ["Premiere Pro", "AI Video Tools", "Canva"],
    description: "Stunning AI-enhanced wedding invitation videos and digital cards. These projects blend traditional wedding aesthetics with modern AI-powered motion graphics, creating memorable digital experiences for special occasions.",
    imageCount: 0,
    videoCaptions: [
      "Nikkah Invitation - Elegant digital invitation with AI-enhanced animations",
      "Wedding Card - Beautifully crafted digital wedding announcement",
      "Mayoun Night - Vibrant celebration invitation with dynamic effects",
      "Wedding Video - Complete wedding invitation package"
    ],
    url: `${SITE_URL}/portfolio/ai-enhanced-digital-media`
  }
];
var brandProjects = [
  {
    id: "optimesh-solutions",
    title: "OptiMesh Solutions",
    subtitle: "Automated 3D Pipelines for AI & XR",
    role: "Lead Brand Designer",
    year: "2025",
    liveUrl: "https://optimeshsolution.lovable.app",
    description: "A bold, high-energy brand identity for a technical agency bridging creative 3D geometry and AI data logic. The visual system communicates precision, speed, and industrial strength through its vibrant orange accents against deep dark backgrounds.",
    designPhilosophy: "The identity is built around the concept of a 'Transform Node'\u2014the icon represents vertices, edges, and control points from 3D software. Dot-matrix patterns symbolize data grids, arrow motifs suggest optimized flow, and the stencil typography reinforces an engineering-first ethos.",
    colors: [
      { name: "Signal Orange", hex: "#F26522" },
      { name: "Carbon Black", hex: "#1A1A2E" },
      { name: "Steel Gray", hex: "#2D2D44" },
      { name: "Cloud White", hex: "#F5F5F5" }
    ],
    typography: { display: "Space Grotesk", body: "Inter", mono: "JetBrains Mono" },
    tools: ["Figma", "Illustrator", "Lovable", "Photoshop"],
    url: `${SITE_URL}/portfolio/optimesh-solutions`
  },
  {
    id: "optisync-vision",
    title: "OptiSync Vision",
    subtitle: "Unified Digital Ecosystem for Medical & Tech Data",
    role: "Identity & UI Designer",
    year: "2025",
    liveUrl: "https://opti-sync-vision.lovable.app",
    description: "A clean, action-oriented brand identity and full UI design system for an ophthalmic inventory management platform. The design balances clinical trust with modern SaaS aesthetics.",
    designPhilosophy: "The 'sync' lettermark features a dynamic circular arrow integrated into the 'S', symbolizing real-time data synchronization. The warm orange dot accent adds a human touch to the otherwise technical blue palette.",
    colors: [
      { name: "Sync Blue", hex: "#2563EB" },
      { name: "Deep Navy", hex: "#0F172A" },
      { name: "Slate Dark", hex: "#1E293B" },
      { name: "Accent Gold", hex: "#F59E0B" }
    ],
    typography: { display: "Inter", body: "Inter" },
    tools: ["Figma", "Lovable", "Supabase", "Tailwind CSS"],
    url: `${SITE_URL}/portfolio/optisync-vision`
  }
];
var services = [
  {
    title: "3D Visuals",
    description: "High-quality product rendering and game assets. From realistic product visualizations to stylized game-ready models, I bring your ideas to life in three dimensions."
  },
  {
    title: "Social Media Design",
    description: "Eye-catching Instagram and LinkedIn visual content that stops the scroll. Strategic designs that communicate your brand's message and drive engagement."
  },
  {
    title: "Brand Identity",
    description: "Complete visual identity systems from logo design to brand guidelines. Create a cohesive look that makes your brand memorable and professional."
  }
];
var about = {
  name: "Imtiyaz Soomro",
  headline: "CS Graduate, 3D Artist & Creative Designer",
  location: "Hyderabad, Pakistan",
  education: "BS Computer Science",
  focus: "3D & Design",
  bio: [
    "I blend the precision of computer science with the artistry of 3D design. With a BS in Computer Science, I bring a unique analytical perspective to creative challenges\u2014combining logic and data-driven thinking with aesthetic sensibility.",
    "My work spans from photorealistic product visualizations for commercial brands to stylized game assets and architectural visualizations. I'm particularly passionate about creating assets that other designers and developers can use in their own projects.",
    "Based in Hyderabad, Pakistan, I work with clients globally to bring their creative visions to life through 3D modeling, graphic design, and visual content creation."
  ],
  skills: [
    "3D Asset Creation",
    "Product Visualization",
    "Isometric Illustration",
    "Hard-surface Modeling",
    "Social Media Graphics",
    "Brand Identity Design"
  ],
  tools: [
    { name: "Maya", category: "3D" },
    { name: "Blender", category: "3D" },
    { name: "Unity", category: "Development" },
    { name: "Photoshop", category: "Design" },
    { name: "Illustrator", category: "Design" },
    { name: "Canva", category: "Design" }
  ],
  contact: {
    email: "iimtiiyazhussainsoomro11@gmail.com",
    linkedin: "https://www.linkedin.com/in/imtiyazsoomro/",
    artstation: "https://www.artstation.com/imtiyazsoomro",
    website: SITE_URL,
    contactPage: `${SITE_URL}/contact`
  }
};

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "List Imtiyaz Soomro's 3D and digital media portfolio projects, optionally filtered by category.",
  inputSchema: {
    category: z.string().optional().describe(
      'Optional category filter, e.g. "Game Assets \u2022 Architecture", "Hard Surface \u2022 Concepts", or "AI-Enhanced Digital Media".'
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? projects.filter((p) => p.category.toLowerCase().includes(category.toLowerCase())) : projects;
    const summary = items.map((p) => ({
      id: p.id,
      title: p.title,
      category: p.category,
      client: p.client,
      year: p.year,
      tools: p.tools,
      url: p.url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { projects: summary }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get the full details of one portfolio project by its id, including description, tools, client and media counts.",
  inputSchema: {
    id: z2.string().min(1).describe('Project id, e.g. "ar-architecture".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const project = projects.find((p) => p.id === id);
    if (!project) {
      return {
        content: [
          {
            type: "text",
            text: `No project with id "${id}". Known ids: ${projects.map((p) => p.id).join(", ")}`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/get-brand-identity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^4.4.3";
var get_brand_identity_default = defineTool3({
  name: "get_brand_identity",
  title: "Get brand identity case studies",
  description: "Get Imtiyaz Soomro's brand identity case studies with color palettes, typography, design philosophy and live links. Omit the id to list them all.",
  inputSchema: {
    id: z3.string().optional().describe('Optional brand project id, e.g. "optimesh-solutions" or "optisync-vision".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    if (!id) {
      return {
        content: [{ type: "text", text: JSON.stringify(brandProjects, null, 2) }],
        structuredContent: { brandProjects }
      };
    }
    const project = brandProjects.find((p) => p.id === id);
    if (!project) {
      return {
        content: [
          {
            type: "text",
            text: `No brand project with id "${id}". Known ids: ${brandProjects.map((p) => p.id).join(", ")}`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { brandProject: project }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
var list_services_default = defineTool4({
  name: "list_services",
  title: "List services offered",
  description: "List the design services Imtiyaz Soomro offers to clients (3D visuals, social media design, brand identity).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-about-and-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
var get_about_and_contact_default = defineTool5({
  name: "get_about_and_contact",
  title: "Get about and contact info",
  description: "Get Imtiyaz Soomro's public bio, location, skills, tool stack and public contact links (email, LinkedIn, ArtStation).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(about, null, 2) }],
    structuredContent: { about }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "imtiyaz-portfolio-mcp",
  title: "Imtiyaz Soomro Portfolio",
  version: "0.1.0",
  instructions: "Public, read-only tools for the portfolio of Imtiyaz Soomro \u2014 3D artist, brand and visual designer. Use `list_projects` and `get_project` for 3D and digital media work, `get_brand_identity` for brand case studies with palettes and typography, `list_services` for the services offered, and `get_about_and_contact` for bio, skills and contact links. All data is already published on the public website.",
  tools: [list_projects_default, get_project_default, get_brand_identity_default, list_services_default, get_about_and_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
